import "@/styles/globals.css";

import { Inter } from "next/font/google";

import { TRPCReactProvider } from "@/trpc/react";
import { cn } from "@/app/_lib/utils";
import Navbar from "./_components/navbar";
import Footer from "./_components/footer";
import { ClerkProvider } from "@clerk/nextjs";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={cn(
            "relative h-full font-sans antialiased",
            inter.className,
          )}
        >
          <Navbar />
          <main className="relative flex min-h-screen flex-col">
            <TRPCReactProvider>
              <div className="flex-1 flex-grow">{children}</div>
            </TRPCReactProvider>
          </main>
          <Footer />
        </body>
      </html>
    </ClerkProvider>
  );
}
